// apps/frontend/src/lib/components/ui/CodeBlock.svelte
<script lang="ts">
	import { cn } from '$lib/utils'
	import Copy from '@lucide/svelte/icons/copy'
	import Check from '@lucide/svelte/icons/check'

	let { value, class: className }: { value: string; class?: string } = $props()
	let copied = $state(false)

	async function copy() {
		if (!navigator.clipboard) return
		await navigator.clipboard.writeText(value)
		copied = true
		setTimeout(() => (copied = false), 1500)
	}
</script>

<div class={cn('relative rounded-md border border-border bg-card', className)}>
	<pre class="overflow-x-auto p-4 pr-12 text-xs font-mono text-foreground">{value}</pre>
	<button
		type="button"
		onclick={copy}
		class="absolute right-2 top-2 inline-flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-foreground"
		aria-label="Copy"
	>
		{#if copied}
			<Check class="h-3.5 w-3.5" />
		{:else}
			<Copy class="h-3.5 w-3.5" />
		{/if}
	</button>
</div>

// apps/frontend/src/components/code-block.tsx
import { useState } from 'react'
import { Check, Copy } from 'lucide-react'
import { Button } from '@/components/ui/button'

export function CodeBlock({ children }: { children: string }) {
  const [copied, setCopied] = useState(false)

  const copy = () => {
    navigator.clipboard.writeText(children)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  return (
    <div className="relative group">
      <pre className="rounded-lg border border-border bg-card px-4 py-3 text-sm overflow-x-auto font-mono text-foreground/90">
        <code>{children}</code>
      </pre>
      <Button
        variant="ghost"
        size="icon"
        className="absolute top-1.5 right-1.5 h-7 w-7 opacity-0 group-hover:opacity-100 transition-opacity"
        onClick={copy}
        aria-label="Copy"
      >
        {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
      </Button>
    </div>
  )
}
