// apps/website/src/lib/components/Footer.svelte
<script lang="ts"></script>

<footer class="border-t border-zinc-800 bg-zinc-950 px-6 py-10 text-zinc-400">
  <div class="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-6 text-sm">
    <div class="flex items-center gap-3">
      <img src="/assets/logo.svg" alt="" class="h-5 w-auto opacity-85" />
      <span>&copy; 2026 Tabularium</span>
      <span class="inline-flex items-center gap-1.5 rounded border border-zinc-700 px-2 py-0.5 text-xs font-medium">
        <span class="h-1.5 w-1.5 rounded-full bg-green-500"></span>
        Apache 2.0
      </span>
    </div>
    <nav class="flex flex-wrap gap-5" aria-label="Footer">
      <a href="https://docs.tabularium.wiki/" class="transition hover:text-brand">Docs</a>
      <a
        href="https://github.com/TabularisDB/tabularium"
        target="_blank"
        rel="noopener noreferrer"
        class="transition hover:text-brand"
      >
        GitHub
      </a>
      <a
        href="https://github.com/TabularisDB/tabularium/blob/main/LICENSE"
        target="_blank"
        rel="noopener noreferrer"
        class="transition hover:text-brand"
      >
        License
      </a>
      <a href="https://docs.tabularium.wiki/install/" class="transition hover:text-brand">Install</a>
      <a href="https://docs.tabularium.wiki/api/" class="transition hover:text-brand">API</a>
    </nav>
  </div>
</footer>

// apps/frontend/src/components/footer.tsx
import { ExternalLink } from 'lucide-react'

export function Footer() {
  return (
    <footer className="border-t border-border mt-24">
      <div className="mx-auto max-w-6xl px-6 py-10 grid gap-6 sm:grid-cols-3 text-sm">
        <div className="space-y-2">
          <div className="font-semibold text-foreground">Tabularis Registry</div>
          <p className="text-muted-foreground">
            The plugin index for the Tabularis database client.
          </p>
        </div>
        <div className="space-y-2">
          <div className="font-medium text-foreground">Developers</div>
          <div className="flex flex-col gap-1.5 text-muted-foreground">
            <a href="/openapi" className="hover:text-foreground inline-flex items-center gap-1.5">
              OpenAPI <ExternalLink className="h-3 w-3" />
            </a>
            <a href="/openapi/json" className="hover:text-foreground inline-flex items-center gap-1.5">
              Spec JSON <ExternalLink className="h-3 w-3" />
            </a>
          </div>
        </div>
        <div className="space-y-2">
          <div className="font-medium text-foreground">Project</div>
          <div className="flex flex-col gap-1.5 text-muted-foreground">
            <a
              href="https://github.com/TabularisDB"
              target="_blank"
              rel="noreferrer"
              className="hover:text-foreground inline-flex items-center gap-1.5"
            >
              GitHub <ExternalLink className="h-3 w-3" />
            </a>
            <a
              href="https://tabularis.dev"
              target="_blank"
              rel="noreferrer"
              className="hover:text-foreground inline-flex items-center gap-1.5"
            >
              tabularis.dev <ExternalLink className="h-3 w-3" />
            </a>
          </div>
        </div>
      </div>
    </footer>
  )
}
