// apps/frontend/src/components/theme-toggle.tsx
import { Moon, Sun, Monitor } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useTheme } from '@/lib/theme'

export function ThemeToggle() {
  const { theme, setTheme } = useTheme()

  const cycle = () => {
    const order = ['light', 'dark', 'system'] as const
    const next = order[(order.indexOf(theme) + 1) % order.length]
    setTheme(next)
  }

  const Icon = theme === 'light' ? Sun : theme === 'dark' ? Moon : Monitor

  return (
    <Button variant="ghost" size="icon" onClick={cycle} aria-label={`Theme: ${theme}`}>
      <Icon className="h-4 w-4" />
    </Button>
  )
}

// apps/frontend/src/lib/components/ThemeToggle.svelte
<script lang="ts">
	import Moon from '@lucide/svelte/icons/moon'
	import Sun from '@lucide/svelte/icons/sun'
	import Monitor from '@lucide/svelte/icons/monitor'
	import { userPrefersMode, setMode } from 'mode-watcher'
	import Button from '$components/ui/Button.svelte'

	function cycle() {
		const next = userPrefersMode.current === 'light' ? 'dark' : userPrefersMode.current === 'dark' ? 'system' : 'light'
		setMode(next)
	}

	const label = $derived(
		userPrefersMode.current === 'system'
			? 'Theme: system (click for light)'
			: userPrefersMode.current === 'dark'
				? 'Theme: dark (click for system)'
				: 'Theme: light (click for dark)',
	)
</script>

<Button variant="ghost" size="icon" aria-label={label} title={label} onclick={cycle}>
	{#if userPrefersMode.current === 'light'}
		<Sun class="h-4 w-4" />
	{:else if userPrefersMode.current === 'dark'}
		<Moon class="h-4 w-4" />
	{:else}
		<Monitor class="h-4 w-4" />
	{/if}
</Button>
