// apps/frontend/src/routes/login/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte'
	import { goto } from '$app/navigation'
	import Button from '$components/ui/Button.svelte'
	import Card from '$components/ui/Card.svelte'
	import CardContent from '$components/ui/CardContent.svelte'
	import CardDescription from '$components/ui/CardDescription.svelte'
	import CardHeader from '$components/ui/CardHeader.svelte'
	import CardTitle from '$components/ui/CardTitle.svelte'
	import ProviderIcon from '$components/brand/ProviderIcon.svelte'
	import { eden } from '$lib/eden'
	import type { InitStatus, ProviderInfo } from '$lib/types'

	let providers = $state<ProviderInfo[] | null>(null)

	onMount(async () => {
		const statusRes = await eden.api.init.status.get()
		const status = (statusRes.data ?? null) as InitStatus | null
		if (status?.requiresInit) {
			goto('/init')
			return
		}
		const providersRes = await eden.auth.providers.get()
		const list = ((providersRes.data ?? { providers: [] }) as { providers: ProviderInfo[] }).providers
		providers = list
	})
</script>

<div class="mx-auto max-w-md px-6 py-20 space-y-8">
	<div class="text-center space-y-2">
		<h1 class="text-3xl font-semibold tracking-tight">Sign in</h1>
		<p class="text-sm text-muted-foreground">Sign in to submit plugins and upvote requests.</p>
	</div>

	<Card>
		<CardHeader>
			<CardTitle class="text-base">Choose a provider</CardTitle>
			<CardDescription>Configured on this instance:</CardDescription>
		</CardHeader>
		<CardContent class="space-y-3">
			{#if providers === null}
				<p class="text-sm text-muted-foreground">Loading…</p>
			{:else if providers.length === 0}
				<p class="text-sm text-muted-foreground">No sign-in providers are configured on this instance yet.</p>
			{:else}
				{#each providers as p (p.id)}
					<Button
						class="w-full justify-start"
						variant="outline"
						onclick={() => (window.location.href = `/auth/${p.id}`)}
					>
						<ProviderIcon kind={p.kind} baseUrl={p.baseUrl} logoUrl={p.logoUrl} class="h-4 w-4" />
						Continue with {p.displayName}
					</Button>
				{/each}
			{/if}
		</CardContent>
	</Card>

	<p class="text-xs text-muted-foreground text-center">
		Tokens are encrypted at rest. We only see your username and an access token used to verify repository ownership when you
		submit a plugin.
	</p>
</div>

// apps/frontend/src/routes/auth/login.tsx
import { useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { Github } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'

export const Route = createFileRoute('/auth/login')({
  component: LoginPage,
})

const BACKEND_URL = import.meta.env.DEV ? 'http://localhost:3000' : ''

function LoginPage() {
  const [forgejo, setForgejo] = useState('')

  const goCodeberg = () => {
    window.location.href = `${BACKEND_URL}/auth/gitea?instance=${encodeURIComponent('https://codeberg.org')}`
  }
  const goForgejo = () => {
    const url = forgejo.trim().replace(/\/$/, '')
    if (!url.startsWith('http')) return
    window.location.href = `${BACKEND_URL}/auth/gitea?instance=${encodeURIComponent(url)}`
  }
  const goGithub = () => {
    window.location.href = `${BACKEND_URL}/auth/github`
  }

  return (
    <div className="mx-auto max-w-md px-6 py-20 space-y-8">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-semibold tracking-tight">Sign in</h1>
        <p className="text-sm text-muted-foreground">
          Sign in to submit plugins and upvote requests.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Choose a provider</CardTitle>
          <CardDescription>
            We support GitHub, Codeberg, and any self-hosted Forgejo/Gitea instance.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <Button onClick={goGithub} className="w-full justify-start">
            <Github className="h-4 w-4" />
            Continue with GitHub
          </Button>

          <Button onClick={goCodeberg} variant="outline" className="w-full justify-start">
            <svg viewBox="0 0 24 24" className="h-4 w-4" fill="currentColor" aria-hidden>
              <path d="M11.955.49A12 12 0 0 0 0 12.49a12 12 0 0 0 1.832 6.373L11.946 5.78l10.226 13.067A12 12 0 0 0 24 12.49a12 12 0 0 0-12-12 12 12 0 0 0-.045 0z"/>
            </svg>
            Continue with Codeberg
          </Button>

          <div className="pt-3 mt-3 border-t border-border space-y-2">
            <Label htmlFor="forgejo" className="text-xs uppercase tracking-wider text-muted-foreground">
              Custom Forgejo / Gitea
            </Label>
            <div className="flex gap-2">
              <Input
                id="forgejo"
                placeholder="https://gitea.example.org"
                value={forgejo}
                onChange={(e) => setForgejo(e.target.value)}
              />
              <Button onClick={goForgejo} variant="outline" disabled={!forgejo.startsWith('http')}>
                Go
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      <p className="text-xs text-muted-foreground text-center">
        We use OAuth for sign-in. The registry only sees your username and a short-lived token
        used to verify repository ownership when you submit a plugin.
      </p>
    </div>
  )
}
