// apps/frontend/src/routes/plugins/index.tsx
import { useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { useQuery, keepPreviousData } from '@tanstack/react-query'
import { Search, ChevronLeft, ChevronRight } from 'lucide-react'
import { api } from '@/lib/api'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { PluginCard } from '@/components/plugin-card'
import { Skeleton } from '@/components/ui/skeleton'

export const Route = createFileRoute('/plugins/')({
  component: PluginsListPage,
})

type PluginSummary = {
  id: string
  name: string
  description: string
  latestVersion: string | null
}
type PluginsResponse = { total: number; page: number; limit: number; plugins: PluginSummary[] }

function PluginsListPage() {
  const [search, setSearch] = useState('')
  const [page, setPage] = useState(1)
  const limit = 12

  const query = useQuery<PluginsResponse>({
    queryKey: ['plugins', { search, page, limit }],
    queryFn: async () => {
      const { data, error } = await (api as any).api.plugins.get({
        query: { search, page: String(page), limit: String(limit) },
      })
      if (error) throw error
      return data as PluginsResponse
    },
    placeholderData: keepPreviousData,
  })

  const totalPages = query.data ? Math.max(1, Math.ceil(query.data.total / limit)) : 1

  return (
    <div className="mx-auto max-w-6xl px-6 py-12 space-y-8">
      <header className="space-y-2">
        <h1 className="text-3xl font-semibold tracking-tight">Plugins</h1>
        <p className="text-muted-foreground">
          Browse {query.data?.total ?? '…'} plugins published to the registry.
        </p>
      </header>

      <div className="relative max-w-xl">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input
          value={search}
          onChange={(e) => {
            setSearch(e.target.value)
            setPage(1)
          }}
          placeholder="Search by name, id, or description…"
          className="pl-9 h-10"
        />
      </div>

      {query.isLoading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {Array.from({ length: 9 }).map((_, i) => (
            <Skeleton key={i} className="h-36 rounded-lg" />
          ))}
        </div>
      ) : query.data && query.data.plugins.length > 0 ? (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {query.data.plugins.map((p) => (
              <PluginCard key={p.id} plugin={p} />
            ))}
          </div>
          {totalPages > 1 && (
            <nav className="flex items-center justify-center gap-2 pt-2" aria-label="Pagination">
              <Button
                variant="outline"
                size="sm"
                disabled={page === 1}
                onClick={() => setPage(page - 1)}
              >
                <ChevronLeft className="h-4 w-4" />
                Previous
              </Button>
              <span className="text-sm text-muted-foreground tabular-nums">
                Page {page} of {totalPages}
              </span>
              <Button
                variant="outline"
                size="sm"
                disabled={page >= totalPages}
                onClick={() => setPage(page + 1)}
              >
                Next
                <ChevronRight className="h-4 w-4" />
              </Button>
            </nav>
          )}
        </>
      ) : (
        <div className="rounded-lg border border-dashed border-border p-12 text-center text-muted-foreground">
          No plugins match your search.
        </div>
      )}
    </div>
  )
}

// apps/frontend/src/routes/plugins/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte'
	import { page } from '$app/state'
	import Search from '@lucide/svelte/icons/search'
	import X from '@lucide/svelte/icons/x'
	import Input from '$components/ui/Input.svelte'
	import Select from '$components/ui/Select.svelte'
	import Skeleton from '$components/ui/Skeleton.svelte'
	import Badge from '$components/ui/Badge.svelte'
	import Button from '$components/ui/Button.svelte'
	import PluginCard from '$components/PluginCard.svelte'
	import { api } from '$lib/api'
	import type { Plugin, PluginListResponse } from '$lib/types'

	let search = $state('')
	let category = $state('')
	let tag = $state('')
	let sort = $state<'updated' | 'new' | 'name' | 'featured'>('updated')
	let onlyFeatured = $state(false)

	let pageNum = $state(1)
	let total = $state(0)
	let plugins = $state<Plugin[] | null>(null)
	let categories = $state<Array<{ value: string; count: number }>>([])
	let loading = $state(true)
	let debounce: ReturnType<typeof setTimeout> | null = null

	// Sync from URL on first mount so deep-links work.
	onMount(() => {
		const url = page.url
		search = url.searchParams.get('search') ?? ''
		category = url.searchParams.get('category') ?? ''
		tag = url.searchParams.get('tag') ?? ''
		const s = url.searchParams.get('sort')
		if (s === 'updated' || s === 'new' || s === 'name' || s === 'featured') sort = s
		onlyFeatured = url.searchParams.get('featured') === '1'
		fetchPlugins()
	})

	async function fetchPlugins() {
		loading = true
		try {
			const q = new URLSearchParams({ page: String(pageNum), limit: '24', sort })
			if (search.trim()) q.set('search', search.trim())
			if (category) q.set('category', category)
			if (tag) q.set('tag', tag)
			if (onlyFeatured) q.set('featured', '1')
			const data = await api.get<PluginListResponse>(`/api/plugins?${q}`)
			plugins = data.plugins
			total = data.total
			categories = data.facets.categories
		} catch {
			plugins = []
			total = 0
		} finally {
			loading = false
		}
	}

	$effect(() => {
		void search
		if (debounce) clearTimeout(debounce)
		debounce = setTimeout(() => {
			pageNum = 1
			fetchPlugins()
		}, 200)
	})

	$effect(() => {
		void category
		void tag
		void sort
		void onlyFeatured
		void pageNum
		fetchPlugins()
	})

	const hasActiveFilters = $derived(Boolean(category || tag || onlyFeatured || search))

	function clearFilters() {
		search = ''
		category = ''
		tag = ''
		onlyFeatured = false
		sort = 'updated'
		pageNum = 1
	}
</script>

<div class="mx-auto max-w-6xl px-6 py-12 space-y-8">
	<header class="space-y-2">
		<h1 class="text-3xl font-semibold tracking-tight">Plugins</h1>
		<p class="text-muted-foreground">Browse the catalog. {total} indexed.</p>
	</header>

	<div class="flex flex-wrap gap-3 items-center">
		<div class="relative flex-1 min-w-[16rem]">
			<Search class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
			<Input bind:value={search} placeholder="Search by name, slug, or description…" class="pl-9" />
		</div>
		<Select bind:value={sort}>
			<option value="updated">Recently updated</option>
			<option value="new">Newest</option>
			<option value="name">A → Z</option>
			<option value="featured">Featured first</option>
		</Select>
		<label class="flex items-center gap-2 text-sm cursor-pointer">
			<input type="checkbox" bind:checked={onlyFeatured} class="h-4 w-4 rounded border-input" />
			<span>Featured only</span>
		</label>
		{#if hasActiveFilters}
			<Button variant="ghost" size="sm" onclick={clearFilters}>
				<X class="h-3.5 w-3.5" />
				Clear
			</Button>
		{/if}
	</div>

	{#if categories.length > 0}
		<div class="flex flex-wrap items-center gap-2">
			<span class="text-xs text-muted-foreground uppercase tracking-wider mr-1">Categories</span>
			{#each categories as cat (cat.value)}
				<button
					type="button"
					onclick={() => (category = category === cat.value ? '' : cat.value)}
					class="text-xs"
					aria-pressed={category === cat.value}
				>
					<Badge variant={category === cat.value ? 'default' : 'outline'} class="cursor-pointer">
						{cat.value} <span class="ml-1 opacity-60">{cat.count}</span>
					</Badge>
				</button>
			{/each}
		</div>
	{/if}

	{#if tag}
		<div class="text-sm">
			<Badge variant="default" class="gap-1">
				#{tag}
				<button type="button" onclick={() => (tag = '')} aria-label="Clear tag" class="-mr-1 ml-1">
					<X class="h-3 w-3" />
				</button>
			</Badge>
		</div>
	{/if}

	{#if loading && !plugins}
		<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
			{#each Array(6) as _}
				<Skeleton class="h-36 rounded-lg" />
			{/each}
		</div>
	{:else if plugins && plugins.length > 0}
		<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
			{#each plugins as p (p.id)}
				<PluginCard plugin={p} />
			{/each}
		</div>
	{:else}
		<div class="rounded-lg border border-dashed border-border p-12 text-center space-y-3">
			<p class="text-muted-foreground">
				{hasActiveFilters ? 'No plugins match these filters.' : 'No plugins yet on this instance.'}
			</p>
			{#if hasActiveFilters}
				<Button variant="outline" size="sm" onclick={clearFilters}>Clear filters</Button>
			{:else}
				<Button size="sm" href="/submit">Submit the first one</Button>
			{/if}
		</div>
	{/if}
</div>
